### PR TITLE
Caffeine dll

### PR DESCRIPTION
**Pull request by cogwheel**
Adding build config & beginnings of caffeine layer

---
This change is [Reviewable](https://reviewable.io/reviews/caffeinetv/webrtc/1)

### CODE REVIEW

**Review by trilorez — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/webrtc/1)* status: 0 of 17 files reviewed, 5 unresolved discussions (waiting on @cogwheel, @davidc604, and @trilorez)

___
*[caffeine/caffeine.h, line 21 at r1](https://reviewable.io/reviews/caffeinetv/webrtc/1#-LNmQ4h72dIzF4W679HA:-LNmQ4h72dIzF4W679HB:b-g1bo99) ([raw file](https://github.com/caffeinetv/webrtc/blob/e519bbdc6be2a09ea5717433478384a479d26c32/caffeine/caffeine.h#L21)):*
> ```objc
> 
> /* Log severities mapped from WebRTC library */
> enum caff_log_severity {
> ```

Since this is our interface, I don't think we necessarily need to follow the obs conventions. How do people feel about typedefing enums and structs? I don't have a strong preference but wanted to bring it up.
___
*[caffeine/caffeine.h, line 34 at r1](https://reviewable.io/reviews/caffeinetv/webrtc/1#-LNmRY10B-UYS3yTo0E4:-LNmRY10B-UYS3yTo0E5:b-8wzhtm) ([raw file](https://github.com/caffeinetv/webrtc/blob/e519bbdc6be2a09ea5717433478384a479d26c32/caffeine/caffeine.h#L34)):*
> ```objc
> 
> /* Callback type for WebRTC log messages */
> typedef void (*caff_log_callback_t)(enum caff_log_severity severity,
> ```

Bikeshed: not a big fan of `_t` suffixes for types
___
*[caffeine/caffeine.h, line 35 at r1](https://reviewable.io/reviews/caffeinetv/webrtc/1#-LNmSlrvCvoteKeVpUGS:-LNmSlrvCvoteKeVpUGT:bma0xdw) ([raw file](https://github.com/caffeinetv/webrtc/blob/e519bbdc6be2a09ea5717433478384a479d26c32/caffeine/caffeine.h#L35)):*
> ```objc
> /* Callback type for WebRTC log messages */
> typedef void (*caff_log_callback_t)(enum caff_log_severity severity,
>                                     char const* message);
> ```

Bikeshed: I like pointers on the right
___
*[caffeine/caffeine.h, line 42 at r1](https://reviewable.io/reviews/caffeinetv/webrtc/1#-LNmRfWI4TlvFAYbBXsg:-LNmRfWI4TlvFAYbBXsh:b-c9in11) ([raw file](https://github.com/caffeinetv/webrtc/blob/e519bbdc6be2a09ea5717433478384a479d26c32/caffeine/caffeine.h#L42)):*
> ```objc
> 
> /* Opaque handles to internal objects */
> typedef void* caff_interface_handle;
> ```

Probably not worth it but an option with slightly more type safety is using an opaque struct
___
*[caffeine/caffeine.cc, line 79 at r1](https://reviewable.io/reviews/caffeinetv/webrtc/1#-LNmS25Z7efp02E3tbC7:-LNmS25Z7efp02E3tbC8:b-woln4l) ([raw file](https://github.com/caffeinetv/webrtc/blob/e519bbdc6be2a09ea5717433478384a479d26c32/caffeine/caffeine.cc#L79)):*
> ```cpp
>   };
> 
>   auto interface = reinterpret_cast<Interface*>(interface_handle);
> ```

I think `static_cast` is preferred here

**Review by cogwheel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/webrtc/1)* status: 0 of 17 files reviewed, 5 unresolved discussions (waiting on @cogwheel, @trilorez, and @davidc604)

___
*[caffeine/caffeine.h, line 21 at r1](https://reviewable.io/reviews/caffeinetv/webrtc/1#-LNmQ4h72dIzF4W679HA:-LNmcSlD79OT8-vC9xtU:bqog80t) ([raw file](https://github.com/caffeinetv/webrtc/blob/e519bbdc6be2a09ea5717433478384a479d26c32/caffeine/caffeine.h#L21)):*
<details><summary><i>Previously, trilorez (Daniel Resnick) wrote…</i></summary><blockquote>

Since this is our interface, I don't think we necessarily need to follow the obs conventions. How do people feel about typedefing enums and structs? I don't have a strong preference but wanted to bring it up.
</blockquote></details>

Agreed
___
*[caffeine/caffeine.h, line 34 at r1](https://reviewable.io/reviews/caffeinetv/webrtc/1#-LNmRY10B-UYS3yTo0E4:-LNmciou94yC2euRJjom:bb6u5lp) ([raw file](https://github.com/caffeinetv/webrtc/blob/e519bbdc6be2a09ea5717433478384a479d26c32/caffeine/caffeine.h#L34)):*
<details><summary><i>Previously, trilorez (Daniel Resnick) wrote…</i></summary><blockquote>

Bikeshed: not a big fan of `_t` suffixes for types
</blockquote></details>

Agreed... definitely copypastaed from experimental code on the obs side.
___
*[caffeine/caffeine.h, line 35 at r1](https://reviewable.io/reviews/caffeinetv/webrtc/1#-LNmSlrvCvoteKeVpUGS:-LNmctjJ3tX5ovMs5oxK:bw3pc0p) ([raw file](https://github.com/caffeinetv/webrtc/blob/e519bbdc6be2a09ea5717433478384a479d26c32/caffeine/caffeine.h#L35)):*
<details><summary><i>Previously, trilorez (Daniel Resnick) wrote…</i></summary><blockquote>

Bikeshed: I like pointers on the right
</blockquote></details>

Until I can get the caffeine layer compiling from outside the webrtc src tree, the PoLR is to use google's clang formatting, which visual studio enforces by default.

FWIW, my preferred style is spaces on both sides.
___
*[caffeine/caffeine.h, line 42 at r1](https://reviewable.io/reviews/caffeinetv/webrtc/1#-LNmRfWI4TlvFAYbBXsg:-LNn8myIDEPtsHJXGnjA:b7cb2i6) ([raw file](https://github.com/caffeinetv/webrtc/blob/e519bbdc6be2a09ea5717433478384a479d26c32/caffeine/caffeine.h#L42)):*
<details><summary><i>Previously, trilorez (Daniel Resnick) wrote…</i></summary><blockquote>

Probably not worth it but an option with slightly more type safety is using an opaque struct
</blockquote></details>

I had considered that originally but went with this for conciseness. Will probably reconsider 
___
*[caffeine/caffeine.cc, line 79 at r1](https://reviewable.io/reviews/caffeinetv/webrtc/1#-LNmS25Z7efp02E3tbC7:-LNn6HPp3B4G1horMacA:bhy9ot6) ([raw file](https://github.com/caffeinetv/webrtc/blob/e519bbdc6be2a09ea5717433478384a479d26c32/caffeine/caffeine.cc#L79)):*
<details><summary><i>Previously, trilorez (Daniel Resnick) wrote…</i></summary><blockquote>

I think `static_cast` is preferred here
</blockquote></details>

Will do.

**Review by cogwheel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/webrtc/1)* status: 0 of 17 files reviewed, 5 unresolved discussions (waiting on @trilorez and @davidc604)

___
*[caffeine/caffeine.h, line 21 at r1](https://reviewable.io/reviews/caffeinetv/webrtc/1#-LNmQ4h72dIzF4W679HA:-LNqKGlk7M0EN6wDGQX0:b-896fix) ([raw file](https://github.com/caffeinetv/webrtc/blob/e519bbdc6be2a09ea5717433478384a479d26c32/caffeine/caffeine.h#L21)):*
<details><summary><i>Previously, cogwheel (Matthew Orlando) wrote…</i></summary><blockquote>

Agreed
</blockquote></details>

Done.
___
*[caffeine/caffeine.h, line 34 at r1](https://reviewable.io/reviews/caffeinetv/webrtc/1#-LNmRY10B-UYS3yTo0E4:-LNqKHPmCbTIKpMnjDZm:b-896fix) ([raw file](https://github.com/caffeinetv/webrtc/blob/e519bbdc6be2a09ea5717433478384a479d26c32/caffeine/caffeine.h#L34)):*
<details><summary><i>Previously, cogwheel (Matthew Orlando) wrote…</i></summary><blockquote>

Agreed... definitely copypastaed from experimental code on the obs side.
</blockquote></details>

Done.
___
*[caffeine/caffeine.h, line 42 at r1](https://reviewable.io/reviews/caffeinetv/webrtc/1#-LNmRfWI4TlvFAYbBXsg:-LNqKIHNAj0yroADq5G6:b-896fix) ([raw file](https://github.com/caffeinetv/webrtc/blob/e519bbdc6be2a09ea5717433478384a479d26c32/caffeine/caffeine.h#L42)):*
<details><summary><i>Previously, cogwheel (Matthew Orlando) wrote…</i></summary><blockquote>

I had considered that originally but went with this for conciseness. Will probably reconsider 
</blockquote></details>

Done.
___
*[caffeine/caffeine.cc, line 79 at r1](https://reviewable.io/reviews/caffeinetv/webrtc/1#-LNmS25Z7efp02E3tbC7:-LNptKOR5TrRsXupVx_b:b-djbn6i) ([raw file](https://github.com/caffeinetv/webrtc/blob/e519bbdc6be2a09ea5717433478384a479d26c32/caffeine/caffeine.cc#L79)):*
<details><summary><i>Previously, cogwheel (Matthew Orlando) wrote…</i></summary><blockquote>

Will do.
</blockquote></details>

Reinterpret's actually needed here after changing to opaque struct type. And I think it is more descriptive for the purpose, emphasizing the opacity of the handle

**Review by trilorez — COMMENTED** [review]
> Reviewed 1 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/caffeinetv/webrtc/1)* status: 0 of 17 files reviewed, all discussions resolved (waiting on @trilorez and @davidc604)

**Comment by cogwheel** [comment]
This is now libcaffeine

**Pull request closed without merging**
